---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Setting up Git Hub
First create your local git, after that create your github repo and execute:  
git remote add origin https://github.com/rpc01/R-Manual.git  
git push -u origin master  

## Import Data
### From csv  
```{r}
data<-read.csv("ALM.MC.csv", header=TRUE)
```
### From yahoo 
```{r, message=FALSE}
library(quantmod)
getSymbols("AAPL",src='yahoo')
```
### From 
## Plot OHLC with plotly
```{r,message=FALSE}
library(plotly)
# annotation
a <- list(text = "COVID19",
          x = '2020-02-20',
          y = 1.02,
          xref = 'x',
          yref = 'paper',
          xanchor = 'left',
          showarrow = FALSE
          )
l <- list(type = line,
          x0 = '2020-02-20',
          x1 = '2020-02-20',
          y0 = 0,
          y1 = 1,
          xref = 'x',
          yref = 'paper',
          line = list(color = 'black',
                      width = 0.5)
          )
df <- data.frame(Date=index(AAPL),coredata(AAPL))
df <- tail(df, 365)

fig <- df %>% plot_ly(x = ~Date, type="ohlc",
          open = ~AAPL.Open, close = ~AAPL.Close,
          high = ~AAPL.High, low = ~AAPL.Low) 
fig <- fig %>% layout(title = "AAPL", 
                      xaxis = list(rangeslider = list(visible = F)), #rangeslider
                      annotations = a,
                      shapes = l)
fig
```

## Compute Returns


